### ISSUE TITLE
Need team for quick development 

### ISSUE THREAD

**Issue by Tura187** [RideSolo/ddkim-verification#2]
Need a team for quick development 
Brainstorm / possibilities/ programing hopefully testing ...

**Comment by RideSolo** [comment]
Can you explain further?

**Comment by RideSolo** [comment]
I cannot follow you logic

**Comment by RideSolo** [comment]
Im probably not the guy for this, I'm just wondering why you commented on this repo 🤯

**Comment by RideSolo** [comment]
What did you figure? Your nonsense?
